apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  labels:
    app: posts
spec:
  containers:
    - name: posts-container
      image: second-image:03
      command: ["node", "index.js"]
      env:
      - name: PostsServiceUrl
        value: "http://localhost:3000"
      - name: VotesServiceUrl
        value: "http://localhost:300"
      - name: PORT
        value: "3000" 
      ports:
      - containerPort: 3000
        protocol: TCP  
---
apiVersion: v1
kind: Pod
metadata:
  name: second-pod
  labels: 
    app: votes
spec:
  containers:
    - name: votes-container
      image: second-image:03
      command: ["node","index.js"]
      env:
        - name: PostsServiceUrl
          value: "http://localhost:3000"
        - name: VotesServiceUrl
          value: "http://localhost:3001"
        - name: PORT
          value: "3001"
      ports:
      - containerPort: 3000
        protocol: TCP  