apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: "{{{M3_NAMESPACE}}}"
spec:
  rules:
   - host: "{{{POST_SERVICE_DNS}}}.{{{M3_HOST_NAME}}}"
     http:
       paths:
        - path: /
          pathType: Prefix
          backend:
           service:
              name: post-service
              port:
                number: 81
    
   - host: "{{{VOTE_SERVICE_DNS}}}.{{{M3_HOST_NAME}}}"
     http:
       paths:
        - path: /
          pathType: Prefix
          backend:
           service:
              name: votes-service
              port:
                number: 80