apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-deployment
  namespace: "{{{"{{{M3_NAMESPACE}}}"M3_NAMESPACE}}}"
  labels:
    app: posts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
      - name: posts
        image: "{{{IMAGE}}}"
        env:
        - name: PostsServiceUrl
          value: "posts-service.{{{M3_NAMESPACE}}}"
        - name: VotesServiceUrl
          value: "votes-service.{{{M3_NAMESPACE}}}"
        - name: PORT
          value: "{{{POST_SERVICE_PORT}}}"
        ports:
        - containerPort: 3000