apiVersion: apps/v1
kind: Deployment
metadata:
  name: votes-deployment
  namespace: "{{{M3_NAMESPACE}}}"
  labels:
    app: votes 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: votes
  template:
    metadata:
      labels:
        app: votes
    spec:
      containers:
      - name: votes
        image: "{{{IMAGE}}}"
        env:
        - name: PostsServiceUrl
          value: "posts-service.{{{M3_NAMESPACE}}}"
        - name: VotesServiceUrl
          value: "votes-service.{{{M3_NAMESPACE}}}"
        - name: PORT
          value: "{{{VOTE_SERVICE_PORT}}}"
        ports:
        - containerPort: 3001